### ISSUE TITLE
could you please provide the csv fiels for 

### ISSUE THREAD

**Issue by MachineGUN001** [zhu-tingfei/PatentNetML#1]
hi, 

Is it possible to provide an address to download those csv files directly, or is it possible to put it in github?
```
data.csv
mini-data.csv
mini-test.csv
mini-train.csv
mini-valid.csv
```
many thanks,

**Comment by zhu-tingfei** [comment]
You can download those files directly from https://drive.google.com/drive/folders/13dpqXqfmAzZPexjlKE8yxfs8ot8TLX3s?usp=sharing.

**Comment by MachineGUN001** [comment]
got it. thanks a lot!

**Comment by MachineGUN001** [comment]
> You can download those files directly from https://drive.google.com/drive/folders/13dpqXqfmAzZPexjlKE8yxfs8ot8TLX3s?usp=sharing.

could you please provide some guidance how to genaterate the file 'data.csv"?
the file data.csv contains

['DrugBank_ID',
 'Name',
 'Drug_Groups',
 'SMILES',
 'Ca_SMILES',
 'PATENT_ID',
 'SMARTS',
 'SCHEMBL',
 'SIMILARITY',
 'P_SMILES',
 'HOMOGENEITY',
 'PCT_FILTERED',
 'P_Ca_SMILES']

many thanks,
